package io.github.cyberpython.libjvlc;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libvlc_media_slave_t extends Structure {
	public Pointer psz_uri;
	/** @see libvlc_media_slave_type_t */
	public int i_type;
	public int i_priority;
	public libvlc_media_slave_t() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("psz_uri", "i_type", "i_priority");
	}
	public libvlc_media_slave_t(Pointer psz_uri, int i_type, int i_priority) {
		super();
		this.psz_uri = psz_uri;
		this.i_type = i_type;
		this.i_priority = i_priority;
	}
	public libvlc_media_slave_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends libvlc_media_slave_t implements Structure.ByReference {
		
	};
	public static class ByValue extends libvlc_media_slave_t implements Structure.ByValue {
		
	};
}
