package io.github.cyberpython.libjvlc;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class libvlc_track_description_t extends Structure {
	public int i_id;
	public Pointer psz_name;
	public libvlc_track_description_t.ByReference p_next;
	public libvlc_track_description_t() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("i_id", "psz_name", "p_next");
	}
	public libvlc_track_description_t(int i_id, Pointer psz_name, libvlc_track_description_t.ByReference p_next) {
		super();
		this.i_id = i_id;
		this.psz_name = psz_name;
		this.p_next = p_next;
	}
	public libvlc_track_description_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends libvlc_track_description_t implements Structure.ByReference {
		
	};
	public static class ByValue extends libvlc_track_description_t implements Structure.ByValue {
		
	};
}
