package io.github.cyberpython.libjvlc;
import io.github.cyberpython.jna.NativeSize;
import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;
import java.nio.IntBuffer;
/**
 * JNA Wrapper for library <b>vlc</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface VlcLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "vlc";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(VlcLibrary.JNA_LIBRARY_NAME);
	public static final VlcLibrary INSTANCE = (VlcLibrary)Native.loadLibrary(VlcLibrary.JNA_LIBRARY_NAME, VlcLibrary.class);
	public static interface libvlc_log_level {
		public static final int LIBVLC_DEBUG = 0;
		public static final int LIBVLC_NOTICE = 2;
		public static final int LIBVLC_WARNING = 3;
		public static final int LIBVLC_ERROR = 4;
	};
	public static interface libvlc_meta_t {
		public static final int libvlc_meta_Title = 0;
		public static final int libvlc_meta_Artist = 1;
		public static final int libvlc_meta_Genre = 2;
		public static final int libvlc_meta_Copyright = 3;
		public static final int libvlc_meta_Album = 4;
		public static final int libvlc_meta_TrackNumber = 5;
		public static final int libvlc_meta_Description = 6;
		public static final int libvlc_meta_Rating = 7;
		public static final int libvlc_meta_Date = 8;
		public static final int libvlc_meta_Setting = 9;
		public static final int libvlc_meta_URL = 10;
		public static final int libvlc_meta_Language = 11;
		public static final int libvlc_meta_NowPlaying = 12;
		public static final int libvlc_meta_Publisher = 13;
		public static final int libvlc_meta_EncodedBy = 14;
		public static final int libvlc_meta_ArtworkURL = 15;
		public static final int libvlc_meta_TrackID = 16;
		public static final int libvlc_meta_TrackTotal = 17;
		public static final int libvlc_meta_Director = 18;
		public static final int libvlc_meta_Season = 19;
		public static final int libvlc_meta_Episode = 20;
		public static final int libvlc_meta_ShowName = 21;
		public static final int libvlc_meta_Actors = 22;
		public static final int libvlc_meta_AlbumArtist = 23;
		public static final int libvlc_meta_DiscNumber = 24;
		public static final int libvlc_meta_DiscTotal = 25;
	};
	public static interface libvlc_state_t {
		public static final int libvlc_NothingSpecial = 0;
		public static final int libvlc_Opening = 1;
		public static final int libvlc_Buffering = 2;
		public static final int libvlc_Playing = 3;
		public static final int libvlc_Paused = 4;
		public static final int libvlc_Stopped = 5;
		public static final int libvlc_Ended = 6;
		public static final int libvlc_Error = 7;
	};
	public static final int libvlc_media_option_trusted = 0x2;
	public static final int libvlc_media_option_unique = 0x100;
	public static interface libvlc_track_type_t {
		public static final int libvlc_track_unknown = -1;
		public static final int libvlc_track_audio = 0;
		public static final int libvlc_track_video = 1;
		public static final int libvlc_track_text = 2;
	};
	public static interface libvlc_video_orient_t {
		public static final int libvlc_video_orient_top_left = 0;
		public static final int libvlc_video_orient_top_right = 1;
		public static final int libvlc_video_orient_bottom_left = 2;
		public static final int libvlc_video_orient_bottom_right = 3;
		public static final int libvlc_video_orient_left_top = 4;
		public static final int libvlc_video_orient_left_bottom = 5;
		public static final int libvlc_video_orient_right_top = 6;
		public static final int libvlc_video_orient_right_bottom = 7;
	};
	public static interface libvlc_video_projection_t {
		public static final int libvlc_video_projection_rectangular = 0;
		public static final int libvlc_video_projection_equirectangular = 1;
		public static final int libvlc_video_projection_cubemap_layout_standard = 0x100;
	};
	public static interface libvlc_media_type_t {
		public static final int libvlc_media_type_unknown = 0;
		public static final int libvlc_media_type_file = 1;
		public static final int libvlc_media_type_directory = 2;
		public static final int libvlc_media_type_disc = 3;
		public static final int libvlc_media_type_stream = 4;
		public static final int libvlc_media_type_playlist = 5;
	};
	public static interface libvlc_media_parse_flag_t {
		public static final int libvlc_media_parse_local = 0x00;
		public static final int libvlc_media_parse_network = 0x01;
		public static final int libvlc_media_fetch_local = 0x02;
		public static final int libvlc_media_fetch_network = 0x04;
		public static final int libvlc_media_do_interact = 0x08;
	};
	public static interface libvlc_media_parsed_status_t {
		public static final int libvlc_media_parsed_status_skipped = 1;
		public static final int libvlc_media_parsed_status_failed = 2;
		public static final int libvlc_media_parsed_status_timeout = 3;
		public static final int libvlc_media_parsed_status_done = 4;
	};
	public static interface libvlc_media_slave_type_t {
		public static final int libvlc_media_slave_type_subtitle = 0;
		public static final int libvlc_media_slave_type_audio = 1;
	};
	public static final int libvlc_title_menu = 0x01;
	public static final int libvlc_title_interactive = 0x02;
	public static interface libvlc_video_marquee_option_t {
		public static final int libvlc_marquee_Enable = 0;
		public static final int libvlc_marquee_Text = 1;
		public static final int libvlc_marquee_Color = 2;
		public static final int libvlc_marquee_Opacity = 3;
		public static final int libvlc_marquee_Position = 4;
		public static final int libvlc_marquee_Refresh = 5;
		public static final int libvlc_marquee_Size = 6;
		public static final int libvlc_marquee_Timeout = 7;
		public static final int libvlc_marquee_X = 8;
		public static final int libvlc_marquee_Y = 9;
	};
	public static interface libvlc_navigate_mode_t {
		public static final int libvlc_navigate_activate = 0;
		public static final int libvlc_navigate_up = 1;
		public static final int libvlc_navigate_down = 2;
		public static final int libvlc_navigate_left = 3;
		public static final int libvlc_navigate_right = 4;
		public static final int libvlc_navigate_popup = 5;
	};
	public static interface libvlc_position_t {
		public static final int libvlc_position_disable = -1;
		public static final int libvlc_position_center = 0;
		public static final int libvlc_position_left = 1;
		public static final int libvlc_position_right = 2;
		public static final int libvlc_position_top = 3;
		public static final int libvlc_position_top_left = 4;
		public static final int libvlc_position_top_right = 5;
		public static final int libvlc_position_bottom = 6;
		public static final int libvlc_position_bottom_left = 7;
		public static final int libvlc_position_bottom_right = 8;
	};
	public static interface libvlc_teletext_key_t {
		public static final char libvlc_teletext_key_red = (char) ('r' << 16);
		public static final char libvlc_teletext_key_green = (char) ('g' << 16);
		public static final char libvlc_teletext_key_yellow = (char) ('y' << 16);
		public static final char libvlc_teletext_key_blue = (char) ('b' << 16);
		public static final char libvlc_teletext_key_index = (char) ('i' << 16);
	};
	public static interface libvlc_video_logo_option_t {
		public static final int libvlc_logo_enable = 0;
		public static final int libvlc_logo_file = 1;
		public static final int libvlc_logo_x = 2;
		public static final int libvlc_logo_y = 3;
		public static final int libvlc_logo_delay = 4;
		public static final int libvlc_logo_repeat = 5;
		public static final int libvlc_logo_opacity = 6;
		public static final int libvlc_logo_position = 7;
	};
	public static interface libvlc_video_adjust_option_t {
		public static final int libvlc_adjust_Enable = 0;
		public static final int libvlc_adjust_Contrast = 1;
		public static final int libvlc_adjust_Brightness = 2;
		public static final int libvlc_adjust_Hue = 3;
		public static final int libvlc_adjust_Saturation = 4;
		public static final int libvlc_adjust_Gamma = 5;
	};
	public static interface libvlc_audio_output_device_types_t {
		public static final int libvlc_AudioOutputDevice_Error = -1;
		public static final int libvlc_AudioOutputDevice_Mono = 1;
		public static final int libvlc_AudioOutputDevice_Stereo = 2;
		public static final int libvlc_AudioOutputDevice_2F2R = 4;
		public static final int libvlc_AudioOutputDevice_3F2R = 5;
		public static final int libvlc_AudioOutputDevice_5_1 = 6;
		public static final int libvlc_AudioOutputDevice_6_1 = 7;
		public static final int libvlc_AudioOutputDevice_7_1 = 8;
		public static final int libvlc_AudioOutputDevice_SPDIF = 10;
	};
	public static interface libvlc_audio_output_channel_t {
		public static final int libvlc_AudioChannel_Error = -1;
		public static final int libvlc_AudioChannel_Stereo = 1;
		public static final int libvlc_AudioChannel_RStereo = 2;
		public static final int libvlc_AudioChannel_Left = 3;
		public static final int libvlc_AudioChannel_Right = 4;
		public static final int libvlc_AudioChannel_Dolbys = 5;
	};
	public static interface libvlc_media_player_role {
		public static final int libvlc_role_None = 0;
		public static final int libvlc_role_Music = 1;
		public static final int libvlc_role_Video = 2;
		public static final int libvlc_role_Communication = 3;
		public static final int libvlc_role_Game = 4;
		public static final int libvlc_role_Notification = 5;
		public static final int libvlc_role_Animation = 6;
		public static final int libvlc_role_Production = 7;
		public static final int libvlc_role_Accessibility = 8;
		public static final int libvlc_role_Test = 9;
	};
	public static final int VLC_LIBVLC_H = (int)1;
	public static final int VLC_LIBVLC_MEDIA_H = (int)1;
	public static final int VLC_LIBVLC_MEDIA_PLAYER_H = (int)1;
	public static final int LIBVLC_VLM_H = (int)1;
	public interface libvlc_callback_t extends Callback {
		void apply(VlcLibrary.libvlc_event_t p_event, Pointer p_data);
	};
	public interface libvlc_log_cb extends Callback {
		void apply(Pointer data, int level, Pointer ctx, Pointer fmt, Object... args);
	};
	public interface libvlc_set_exit_handler_cb_callback extends Callback {
		void apply(Pointer voidPtr1);
	};
	public interface libvlc_media_open_cb extends Callback {
		int apply(Pointer opaque, PointerByReference datap, LongByReference sizep);
	};
	public interface ssize_t extends Callback {
		VlcLibrary.ssize_t_callback apply(Pointer libvlc_media_read_cb);
	};
	public interface libvlc_media_seek_cb extends Callback {
		int apply(Pointer opaque, long offset);
	};
	public interface libvlc_media_close_cb extends Callback {
		void apply(Pointer opaque);
	};
	public interface ssize_t_callback extends Callback {
		int apply(Pointer opaque, Pointer buf, NativeSize len);
	};
	public interface libvlc_video_lock_cb extends Callback {
		Pointer apply(Pointer opaque, PointerByReference planes);
	};
	public interface libvlc_video_unlock_cb extends Callback {
		void apply(Pointer opaque, Pointer picture, PointerByReference planes);
	};
	public interface libvlc_video_display_cb extends Callback {
		void apply(Pointer opaque, Pointer picture);
	};
	public interface libvlc_video_format_cb extends Callback {
		int apply(PointerByReference opaque, Pointer chroma, IntByReference width, IntByReference height, IntByReference pitches, IntByReference lines);
	};
	public interface libvlc_video_cleanup_cb extends Callback {
		void apply(Pointer opaque);
	};
	public interface libvlc_audio_play_cb extends Callback {
		void apply(Pointer data, Pointer samples, int count, long pts);
	};
	public interface libvlc_audio_pause_cb extends Callback {
		void apply(Pointer data, long pts);
	};
	public interface libvlc_audio_resume_cb extends Callback {
		void apply(Pointer data, long pts);
	};
	public interface libvlc_audio_flush_cb extends Callback {
		void apply(Pointer data, long pts);
	};
	public interface libvlc_audio_drain_cb extends Callback {
		void apply(Pointer data);
	};
	public interface libvlc_audio_set_volume_cb extends Callback {
		void apply(Pointer data, float volume, byte mute);
	};
	public interface libvlc_audio_setup_cb extends Callback {
		int apply(PointerByReference data, Pointer format, IntByReference rate, IntByReference channels);
	};
	public interface libvlc_audio_cleanup_cb extends Callback {
		void apply(Pointer data);
	};
	String libvlc_errmsg();
	void libvlc_clearerr();
	@Deprecated 
	String libvlc_vprinterr(Pointer fmt, Object... ap);
	String libvlc_vprinterr(String fmt, Object... ap);
	@Deprecated 
	String libvlc_printerr(Pointer fmt, Object... varArgs1);
	String libvlc_printerr(String fmt, Object... varArgs1);
	@Deprecated 
	PointerByReference libvlc_new(int argc, PointerByReference argv);
	PointerByReference libvlc_new(int argc, String argv[]);
	@Deprecated 
	void libvlc_release(Pointer p_instance);
	void libvlc_release(PointerByReference p_instance);
	@Deprecated 
	void libvlc_retain(Pointer p_instance);
	void libvlc_retain(PointerByReference p_instance);
	@Deprecated 
	int libvlc_add_intf(Pointer p_instance, Pointer name);
	int libvlc_add_intf(PointerByReference p_instance, String name);
	int libvlc_add_intf(PointerByReference p_instance, Pointer name);
	@Deprecated 
	void libvlc_set_exit_handler(Pointer p_instance, VlcLibrary.libvlc_set_exit_handler_cb_callback cb, Pointer opaque);
	void libvlc_set_exit_handler(PointerByReference p_instance, VlcLibrary.libvlc_set_exit_handler_cb_callback cb, Pointer opaque);
	@Deprecated 
	void libvlc_set_user_agent(Pointer p_instance, Pointer name, Pointer http);
	void libvlc_set_user_agent(PointerByReference p_instance, String name, String http);
	void libvlc_set_user_agent(PointerByReference p_instance, Pointer name, Pointer http);
	@Deprecated 
	void libvlc_set_app_id(Pointer p_instance, Pointer id, Pointer version, Pointer icon);
	void libvlc_set_app_id(PointerByReference p_instance, String id, String version, String icon);
	void libvlc_set_app_id(PointerByReference p_instance, Pointer id, Pointer version, Pointer icon);
	String libvlc_get_version();
	String libvlc_get_compiler();
	String libvlc_get_changeset();
	void libvlc_free(Pointer ptr);
	@Deprecated 
	int libvlc_event_attach(Pointer p_event_manager, int i_event_type, VlcLibrary.libvlc_callback_t f_callback, Pointer user_data);
	int libvlc_event_attach(PointerByReference p_event_manager, int i_event_type, VlcLibrary.libvlc_callback_t f_callback, Pointer user_data);
	@Deprecated 
	void libvlc_event_detach(Pointer p_event_manager, int i_event_type, VlcLibrary.libvlc_callback_t f_callback, Pointer p_user_data);
	void libvlc_event_detach(PointerByReference p_event_manager, int i_event_type, VlcLibrary.libvlc_callback_t f_callback, Pointer p_user_data);
	String libvlc_event_type_name(int event_type);
	@Deprecated 
	void libvlc_log_get_context(Pointer ctx, PointerByReference module, PointerByReference file, IntByReference line);
	void libvlc_log_get_context(PointerByReference ctx, String module[], String file[], IntBuffer line);
	void libvlc_log_get_context(PointerByReference ctx, PointerByReference module, PointerByReference file, IntByReference line);
	@Deprecated 
	void libvlc_log_get_object(Pointer ctx, PointerByReference name, PointerByReference header, PointerByReference id);
	void libvlc_log_get_object(PointerByReference ctx, String name[], String header[], PointerByReference id);
	void libvlc_log_get_object(PointerByReference ctx, PointerByReference name, PointerByReference header, PointerByReference id);
	@Deprecated 
	void libvlc_log_unset(Pointer p_instance);
	void libvlc_log_unset(PointerByReference p_instance);
	@Deprecated 
	void libvlc_log_set(Pointer p_instance, VlcLibrary.libvlc_log_cb cb, Pointer data);
	void libvlc_log_set(PointerByReference p_instance, VlcLibrary.libvlc_log_cb cb, Pointer data);
	@Deprecated 
	void libvlc_log_set_file(Pointer p_instance, Pointer stream);
	void libvlc_log_set_file(PointerByReference p_instance, PointerByReference stream);
	void libvlc_module_description_list_release(libvlc_module_description_t p_list);
	@Deprecated 
	libvlc_module_description_t libvlc_audio_filter_list_get(Pointer p_instance);
	libvlc_module_description_t libvlc_audio_filter_list_get(PointerByReference p_instance);
	@Deprecated 
	libvlc_module_description_t libvlc_video_filter_list_get(Pointer p_instance);
	libvlc_module_description_t libvlc_video_filter_list_get(PointerByReference p_instance);
	long libvlc_clock();
	@Deprecated 
	PointerByReference libvlc_media_new_location(Pointer p_instance, Pointer psz_mrl);
	PointerByReference libvlc_media_new_location(PointerByReference p_instance, String psz_mrl);
	PointerByReference libvlc_media_new_location(PointerByReference p_instance, Pointer psz_mrl);
	@Deprecated 
	PointerByReference libvlc_media_new_path(Pointer p_instance, Pointer path);
	PointerByReference libvlc_media_new_path(PointerByReference p_instance, String path);
	PointerByReference libvlc_media_new_path(PointerByReference p_instance, Pointer path);
	@Deprecated 
	PointerByReference libvlc_media_new_fd(Pointer p_instance, int fd);
	PointerByReference libvlc_media_new_fd(PointerByReference p_instance, int fd);
	@Deprecated 
	PointerByReference libvlc_media_new_callbacks(Pointer instance, VlcLibrary.libvlc_media_open_cb open_cb, VlcLibrary.libvlc_media_read_cb read_cb, VlcLibrary.libvlc_media_seek_cb seek_cb, VlcLibrary.libvlc_media_close_cb close_cb, Pointer opaque);
	PointerByReference libvlc_media_new_callbacks(PointerByReference instance, VlcLibrary.libvlc_media_open_cb open_cb, VlcLibrary.libvlc_media_read_cb read_cb, VlcLibrary.libvlc_media_seek_cb seek_cb, VlcLibrary.libvlc_media_close_cb close_cb, Pointer opaque);
	@Deprecated 
	PointerByReference libvlc_media_new_as_node(Pointer p_instance, Pointer psz_name);
	PointerByReference libvlc_media_new_as_node(PointerByReference p_instance, String psz_name);
	PointerByReference libvlc_media_new_as_node(PointerByReference p_instance, Pointer psz_name);
	@Deprecated 
	void libvlc_media_add_option(Pointer p_md, Pointer psz_options);
	void libvlc_media_add_option(PointerByReference p_md, String psz_options);
	void libvlc_media_add_option(PointerByReference p_md, Pointer psz_options);
	@Deprecated 
	void libvlc_media_add_option_flag(Pointer p_md, Pointer psz_options, int i_flags);
	void libvlc_media_add_option_flag(PointerByReference p_md, String psz_options, int i_flags);
	void libvlc_media_add_option_flag(PointerByReference p_md, Pointer psz_options, int i_flags);
	@Deprecated 
	void libvlc_media_retain(Pointer p_md);
	void libvlc_media_retain(PointerByReference p_md);
	@Deprecated 
	void libvlc_media_release(Pointer p_md);
	void libvlc_media_release(PointerByReference p_md);
	@Deprecated 
	Pointer libvlc_media_get_mrl(Pointer p_md);
	Pointer libvlc_media_get_mrl(PointerByReference p_md);
	@Deprecated 
	PointerByReference libvlc_media_duplicate(Pointer p_md);
	PointerByReference libvlc_media_duplicate(PointerByReference p_md);
	@Deprecated 
	Pointer libvlc_media_get_meta(Pointer p_md, int e_meta);
	Pointer libvlc_media_get_meta(PointerByReference p_md, int e_meta);
	@Deprecated 
	void libvlc_media_set_meta(Pointer p_md, int e_meta, Pointer psz_value);
	void libvlc_media_set_meta(PointerByReference p_md, int e_meta, String psz_value);
	void libvlc_media_set_meta(PointerByReference p_md, int e_meta, Pointer psz_value);
	@Deprecated 
	int libvlc_media_save_meta(Pointer p_md);
	int libvlc_media_save_meta(PointerByReference p_md);
	@Deprecated 
	int libvlc_media_get_state(Pointer p_md);
	int libvlc_media_get_state(PointerByReference p_md);
	@Deprecated 
	int libvlc_media_get_stats(Pointer p_md, libvlc_media_stats_t p_stats);
	int libvlc_media_get_stats(PointerByReference p_md, libvlc_media_stats_t p_stats);
	@Deprecated 
	VlcLibrary.libvlc_media_list_t libvlc_media_subitems(Pointer p_md);
	VlcLibrary.libvlc_media_list_t libvlc_media_subitems(PointerByReference p_md);
	@Deprecated 
	PointerByReference libvlc_media_event_manager(Pointer p_md);
	PointerByReference libvlc_media_event_manager(PointerByReference p_md);
	@Deprecated 
	long libvlc_media_get_duration(Pointer p_md);
	long libvlc_media_get_duration(PointerByReference p_md);
	@Deprecated 
	int libvlc_media_parse(PointerByReference p_md);
	int libvlc_media_parse_with_options(PointerByReference p_md, int parse_flag, int timeout);
	@Deprecated 
	void libvlc_media_parse_stop(Pointer p_md);
	void libvlc_media_parse_stop(PointerByReference p_md);
	@Deprecated 
	int libvlc_media_get_parsed_status(Pointer p_md);
	int libvlc_media_get_parsed_status(PointerByReference p_md);
	@Deprecated 
	void libvlc_media_set_user_data(Pointer p_md, Pointer p_new_user_data);
	void libvlc_media_set_user_data(PointerByReference p_md, Pointer p_new_user_data);
	@Deprecated 
	Pointer libvlc_media_get_user_data(Pointer p_md);
	Pointer libvlc_media_get_user_data(PointerByReference p_md);
	@Deprecated 
	int libvlc_media_tracks_get(Pointer p_md, PointerByReference tracks);
	int libvlc_media_tracks_get(PointerByReference p_md, PointerByReference tracks);
	String libvlc_media_get_codec_description(int i_type, int i_codec);
	@Deprecated 
	void libvlc_media_tracks_release(PointerByReference p_tracks, int i_count);
	void libvlc_media_tracks_release(io.github.cyberpython.libjvlc.libvlc_media_track_t.ByReference p_tracks[], int i_count);
	@Deprecated 
	int libvlc_media_get_type(Pointer p_md);
	int libvlc_media_get_type(PointerByReference p_md);
	@Deprecated 
	int libvlc_media_slaves_add(Pointer p_md, int i_type, int i_priority, Pointer psz_uri);
	int libvlc_media_slaves_add(PointerByReference p_md, int i_type, int i_priority, String psz_uri);
	int libvlc_media_slaves_add(PointerByReference p_md, int i_type, int i_priority, Pointer psz_uri);
	@Deprecated 
	void libvlc_media_slaves_clear(Pointer p_md);
	void libvlc_media_slaves_clear(PointerByReference p_md);
	@Deprecated 
	int libvlc_media_slaves_get(Pointer p_md, PointerByReference ppp_slaves);
	int libvlc_media_slaves_get(PointerByReference p_md, PointerByReference ppp_slaves);
	@Deprecated 
	void libvlc_media_slaves_release(PointerByReference pp_slaves, int i_count);
	void libvlc_media_slaves_release(io.github.cyberpython.libjvlc.libvlc_media_slave_t.ByReference pp_slaves[], int i_count);
	@Deprecated 
	PointerByReference libvlc_media_player_new(Pointer p_libvlc_instance);
	PointerByReference libvlc_media_player_new(PointerByReference p_libvlc_instance);
	@Deprecated 
	PointerByReference libvlc_media_player_new_from_media(Pointer p_md);
	PointerByReference libvlc_media_player_new_from_media(PointerByReference p_md);
	@Deprecated 
	void libvlc_media_player_release(Pointer p_mi);
	void libvlc_media_player_release(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_retain(Pointer p_mi);
	void libvlc_media_player_retain(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_set_media(Pointer p_mi, Pointer p_md);
	void libvlc_media_player_set_media(PointerByReference p_mi, PointerByReference p_md);
	@Deprecated 
	PointerByReference libvlc_media_player_get_media(Pointer p_mi);
	PointerByReference libvlc_media_player_get_media(PointerByReference p_mi);
	@Deprecated 
	PointerByReference libvlc_media_player_event_manager(Pointer p_mi);
	PointerByReference libvlc_media_player_event_manager(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_is_playing(Pointer p_mi);
	int libvlc_media_player_is_playing(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_play(Pointer p_mi);
	int libvlc_media_player_play(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_set_pause(Pointer mp, int do_pause);
	void libvlc_media_player_set_pause(PointerByReference mp, int do_pause);
	@Deprecated 
	void libvlc_media_player_pause(Pointer p_mi);
	void libvlc_media_player_pause(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_stop(Pointer p_mi);
	void libvlc_media_player_stop(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_set_renderer(Pointer p_mi, VlcLibrary.libvlc_renderer_item_t p_item);
	int libvlc_media_player_set_renderer(PointerByReference p_mi, VlcLibrary.libvlc_renderer_item_t p_item[]);
	int libvlc_media_player_set_renderer(PointerByReference p_mi, VlcLibrary.libvlc_renderer_item_t p_item);
	@Deprecated 
	void libvlc_video_set_callbacks(Pointer mp, VlcLibrary.libvlc_video_lock_cb lock, VlcLibrary.libvlc_video_unlock_cb unlock, VlcLibrary.libvlc_video_display_cb display, Pointer opaque);
	void libvlc_video_set_callbacks(PointerByReference mp, VlcLibrary.libvlc_video_lock_cb lock, VlcLibrary.libvlc_video_unlock_cb unlock, VlcLibrary.libvlc_video_display_cb display, Pointer opaque);
	@Deprecated 
	void libvlc_video_set_format(Pointer mp, Pointer chroma, int width, int height, int pitch);
	void libvlc_video_set_format(PointerByReference mp, String chroma, int width, int height, int pitch);
	void libvlc_video_set_format(PointerByReference mp, Pointer chroma, int width, int height, int pitch);
	@Deprecated 
	void libvlc_video_set_format_callbacks(Pointer mp, VlcLibrary.libvlc_video_format_cb setup, VlcLibrary.libvlc_video_cleanup_cb cleanup);
	void libvlc_video_set_format_callbacks(PointerByReference mp, VlcLibrary.libvlc_video_format_cb setup, VlcLibrary.libvlc_video_cleanup_cb cleanup);
	@Deprecated 
	void libvlc_media_player_set_nsobject(Pointer p_mi, Pointer drawable);
	void libvlc_media_player_set_nsobject(PointerByReference p_mi, Pointer drawable);
	@Deprecated 
	Pointer libvlc_media_player_get_nsobject(Pointer p_mi);
	Pointer libvlc_media_player_get_nsobject(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_set_xwindow(Pointer p_mi, int drawable);
	void libvlc_media_player_set_xwindow(PointerByReference p_mi, int drawable);
	@Deprecated 
	int libvlc_media_player_get_xwindow(Pointer p_mi);
	int libvlc_media_player_get_xwindow(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_set_hwnd(Pointer p_mi, Pointer drawable);
	void libvlc_media_player_set_hwnd(PointerByReference p_mi, Pointer drawable);
	@Deprecated 
	Pointer libvlc_media_player_get_hwnd(Pointer p_mi);
	Pointer libvlc_media_player_get_hwnd(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_set_android_context(Pointer p_mi, Pointer p_awindow_handler);
	void libvlc_media_player_set_android_context(PointerByReference p_mi, Pointer p_awindow_handler);
	@Deprecated 
	int libvlc_media_player_set_evas_object(Pointer p_mi, Pointer p_evas_object);
	int libvlc_media_player_set_evas_object(PointerByReference p_mi, Pointer p_evas_object);
	@Deprecated 
	void libvlc_audio_set_callbacks(Pointer mp, VlcLibrary.libvlc_audio_play_cb play, VlcLibrary.libvlc_audio_pause_cb pause, VlcLibrary.libvlc_audio_resume_cb resume, VlcLibrary.libvlc_audio_flush_cb flush, VlcLibrary.libvlc_audio_drain_cb drain, Pointer opaque);
	void libvlc_audio_set_callbacks(PointerByReference mp, VlcLibrary.libvlc_audio_play_cb play, VlcLibrary.libvlc_audio_pause_cb pause, VlcLibrary.libvlc_audio_resume_cb resume, VlcLibrary.libvlc_audio_flush_cb flush, VlcLibrary.libvlc_audio_drain_cb drain, Pointer opaque);
	@Deprecated 
	void libvlc_audio_set_volume_callback(Pointer mp, VlcLibrary.libvlc_audio_set_volume_cb set_volume);
	void libvlc_audio_set_volume_callback(PointerByReference mp, VlcLibrary.libvlc_audio_set_volume_cb set_volume);
	@Deprecated 
	void libvlc_audio_set_format_callbacks(Pointer mp, VlcLibrary.libvlc_audio_setup_cb setup, VlcLibrary.libvlc_audio_cleanup_cb cleanup);
	void libvlc_audio_set_format_callbacks(PointerByReference mp, VlcLibrary.libvlc_audio_setup_cb setup, VlcLibrary.libvlc_audio_cleanup_cb cleanup);
	@Deprecated 
	void libvlc_audio_set_format(Pointer mp, Pointer format, int rate, int channels);
	void libvlc_audio_set_format(PointerByReference mp, String format, int rate, int channels);
	void libvlc_audio_set_format(PointerByReference mp, Pointer format, int rate, int channels);
	@Deprecated 
	long libvlc_media_player_get_length(Pointer p_mi);
	long libvlc_media_player_get_length(PointerByReference p_mi);
	@Deprecated 
	long libvlc_media_player_get_time(Pointer p_mi);
	long libvlc_media_player_get_time(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_set_time(Pointer p_mi, long i_time);
	void libvlc_media_player_set_time(PointerByReference p_mi, long i_time);
	@Deprecated 
	float libvlc_media_player_get_position(Pointer p_mi);
	float libvlc_media_player_get_position(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_set_position(Pointer p_mi, float f_pos);
	void libvlc_media_player_set_position(PointerByReference p_mi, float f_pos);
	@Deprecated 
	void libvlc_media_player_set_chapter(Pointer p_mi, int i_chapter);
	void libvlc_media_player_set_chapter(PointerByReference p_mi, int i_chapter);
	@Deprecated 
	int libvlc_media_player_get_chapter(Pointer p_mi);
	int libvlc_media_player_get_chapter(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_get_chapter_count(Pointer p_mi);
	int libvlc_media_player_get_chapter_count(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_will_play(Pointer p_mi);
	int libvlc_media_player_will_play(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_get_chapter_count_for_title(Pointer p_mi, int i_title);
	int libvlc_media_player_get_chapter_count_for_title(PointerByReference p_mi, int i_title);
	@Deprecated 
	void libvlc_media_player_set_title(Pointer p_mi, int i_title);
	void libvlc_media_player_set_title(PointerByReference p_mi, int i_title);
	@Deprecated 
	int libvlc_media_player_get_title(Pointer p_mi);
	int libvlc_media_player_get_title(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_get_title_count(Pointer p_mi);
	int libvlc_media_player_get_title_count(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_previous_chapter(Pointer p_mi);
	void libvlc_media_player_previous_chapter(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_next_chapter(Pointer p_mi);
	void libvlc_media_player_next_chapter(PointerByReference p_mi);
	@Deprecated 
	float libvlc_media_player_get_rate(Pointer p_mi);
	float libvlc_media_player_get_rate(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_set_rate(Pointer p_mi, float rate);
	int libvlc_media_player_set_rate(PointerByReference p_mi, float rate);
	@Deprecated 
	int libvlc_media_player_get_state(Pointer p_mi);
	int libvlc_media_player_get_state(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_has_vout(Pointer p_mi);
	int libvlc_media_player_has_vout(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_is_seekable(Pointer p_mi);
	int libvlc_media_player_is_seekable(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_can_pause(Pointer p_mi);
	int libvlc_media_player_can_pause(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_program_scrambled(Pointer p_mi);
	int libvlc_media_player_program_scrambled(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_next_frame(Pointer p_mi);
	void libvlc_media_player_next_frame(PointerByReference p_mi);
	@Deprecated 
	void libvlc_media_player_navigate(Pointer p_mi, int navigate);
	void libvlc_media_player_navigate(PointerByReference p_mi, int navigate);
	@Deprecated 
	void libvlc_media_player_set_video_title_display(Pointer p_mi, int position, int timeout);
	void libvlc_media_player_set_video_title_display(PointerByReference p_mi, int position, int timeout);
	@Deprecated 
	int libvlc_media_player_add_slave(Pointer p_mi, int i_type, Pointer psz_uri, byte b_select);
	int libvlc_media_player_add_slave(PointerByReference p_mi, int i_type, String psz_uri, byte b_select);
	int libvlc_media_player_add_slave(PointerByReference p_mi, int i_type, Pointer psz_uri, byte b_select);
	void libvlc_track_description_list_release(libvlc_track_description_t p_track_description);
	@Deprecated 
	void libvlc_toggle_fullscreen(Pointer p_mi);
	void libvlc_toggle_fullscreen(PointerByReference p_mi);
	@Deprecated 
	void libvlc_set_fullscreen(Pointer p_mi, int b_fullscreen);
	void libvlc_set_fullscreen(PointerByReference p_mi, int b_fullscreen);
	@Deprecated 
	int libvlc_get_fullscreen(Pointer p_mi);
	int libvlc_get_fullscreen(PointerByReference p_mi);
	@Deprecated 
	void libvlc_video_set_key_input(Pointer p_mi, int on);
	void libvlc_video_set_key_input(PointerByReference p_mi, int on);
	@Deprecated 
	void libvlc_video_set_mouse_input(Pointer p_mi, int on);
	void libvlc_video_set_mouse_input(PointerByReference p_mi, int on);
	@Deprecated 
	int libvlc_video_get_size(Pointer p_mi, int num, IntByReference px, IntByReference py);
	int libvlc_video_get_size(PointerByReference p_mi, int num, IntBuffer px, IntBuffer py);
	int libvlc_video_get_size(PointerByReference p_mi, int num, IntByReference px, IntByReference py);
	@Deprecated 
	int libvlc_video_get_cursor(Pointer p_mi, int num, IntByReference px, IntByReference py);
	int libvlc_video_get_cursor(PointerByReference p_mi, int num, IntBuffer px, IntBuffer py);
	int libvlc_video_get_cursor(PointerByReference p_mi, int num, IntByReference px, IntByReference py);
	@Deprecated 
	float libvlc_video_get_scale(Pointer p_mi);
	float libvlc_video_get_scale(PointerByReference p_mi);
	@Deprecated 
	void libvlc_video_set_scale(Pointer p_mi, float f_factor);
	void libvlc_video_set_scale(PointerByReference p_mi, float f_factor);
	@Deprecated 
	Pointer libvlc_video_get_aspect_ratio(Pointer p_mi);
	Pointer libvlc_video_get_aspect_ratio(PointerByReference p_mi);
	@Deprecated 
	void libvlc_video_set_aspect_ratio(Pointer p_mi, Pointer psz_aspect);
	void libvlc_video_set_aspect_ratio(PointerByReference p_mi, String psz_aspect);
	void libvlc_video_set_aspect_ratio(PointerByReference p_mi, Pointer psz_aspect);
	libvlc_video_viewpoint_t libvlc_video_new_viewpoint();
	@Deprecated 
	int libvlc_video_update_viewpoint(Pointer p_mi, libvlc_video_viewpoint_t p_viewpoint, byte b_absolute);
	int libvlc_video_update_viewpoint(PointerByReference p_mi, libvlc_video_viewpoint_t p_viewpoint, byte b_absolute);
	@Deprecated 
	int libvlc_video_get_spu(Pointer p_mi);
	int libvlc_video_get_spu(PointerByReference p_mi);
	@Deprecated 
	int libvlc_video_get_spu_count(Pointer p_mi);
	int libvlc_video_get_spu_count(PointerByReference p_mi);
	@Deprecated 
	libvlc_track_description_t libvlc_video_get_spu_description(Pointer p_mi);
	libvlc_track_description_t libvlc_video_get_spu_description(PointerByReference p_mi);
	@Deprecated 
	int libvlc_video_set_spu(Pointer p_mi, int i_spu);
	int libvlc_video_set_spu(PointerByReference p_mi, int i_spu);
	@Deprecated 
	long libvlc_video_get_spu_delay(Pointer p_mi);
	long libvlc_video_get_spu_delay(PointerByReference p_mi);
	@Deprecated 
	int libvlc_video_set_spu_delay(Pointer p_mi, long i_delay);
	int libvlc_video_set_spu_delay(PointerByReference p_mi, long i_delay);
	@Deprecated 
	int libvlc_media_player_get_full_title_descriptions(Pointer p_mi, PointerByReference titles);
	int libvlc_media_player_get_full_title_descriptions(PointerByReference p_mi, PointerByReference titles);
	@Deprecated 
	void libvlc_title_descriptions_release(PointerByReference p_titles, int i_count);
	void libvlc_title_descriptions_release(io.github.cyberpython.libjvlc.libvlc_title_description_t.ByReference p_titles[], int i_count);
	@Deprecated 
	int libvlc_media_player_get_full_chapter_descriptions(Pointer p_mi, int i_chapters_of_title, PointerByReference pp_chapters);
	int libvlc_media_player_get_full_chapter_descriptions(PointerByReference p_mi, int i_chapters_of_title, PointerByReference pp_chapters);
	@Deprecated 
	void libvlc_chapter_descriptions_release(PointerByReference p_chapters, int i_count);
	void libvlc_chapter_descriptions_release(io.github.cyberpython.libjvlc.libvlc_chapter_description_t.ByReference p_chapters[], int i_count);
	@Deprecated 
	Pointer libvlc_video_get_crop_geometry(Pointer p_mi);
	Pointer libvlc_video_get_crop_geometry(PointerByReference p_mi);
	@Deprecated 
	void libvlc_video_set_crop_geometry(Pointer p_mi, Pointer psz_geometry);
	void libvlc_video_set_crop_geometry(PointerByReference p_mi, String psz_geometry);
	void libvlc_video_set_crop_geometry(PointerByReference p_mi, Pointer psz_geometry);
	@Deprecated 
	int libvlc_video_get_teletext(Pointer p_mi);
	int libvlc_video_get_teletext(PointerByReference p_mi);
	@Deprecated 
	void libvlc_video_set_teletext(Pointer p_mi, int i_page);
	void libvlc_video_set_teletext(PointerByReference p_mi, int i_page);
	@Deprecated 
	int libvlc_video_get_track_count(Pointer p_mi);
	int libvlc_video_get_track_count(PointerByReference p_mi);
	@Deprecated 
	libvlc_track_description_t libvlc_video_get_track_description(Pointer p_mi);
	libvlc_track_description_t libvlc_video_get_track_description(PointerByReference p_mi);
	@Deprecated 
	int libvlc_video_get_track(Pointer p_mi);
	int libvlc_video_get_track(PointerByReference p_mi);
	@Deprecated 
	int libvlc_video_set_track(Pointer p_mi, int i_track);
	int libvlc_video_set_track(PointerByReference p_mi, int i_track);
	@Deprecated 
	int libvlc_video_take_snapshot(Pointer p_mi, int num, Pointer psz_filepath, int i_width, int i_height);
	int libvlc_video_take_snapshot(PointerByReference p_mi, int num, String psz_filepath, int i_width, int i_height);
	int libvlc_video_take_snapshot(PointerByReference p_mi, int num, Pointer psz_filepath, int i_width, int i_height);
	@Deprecated 
	void libvlc_video_set_deinterlace(Pointer p_mi, Pointer psz_mode);
	void libvlc_video_set_deinterlace(PointerByReference p_mi, String psz_mode);
	void libvlc_video_set_deinterlace(PointerByReference p_mi, Pointer psz_mode);
	@Deprecated 
	int libvlc_video_get_marquee_int(Pointer p_mi, int option);
	int libvlc_video_get_marquee_int(PointerByReference p_mi, int option);
	@Deprecated 
	Pointer libvlc_video_get_marquee_string(Pointer p_mi, int option);
	Pointer libvlc_video_get_marquee_string(PointerByReference p_mi, int option);
	@Deprecated 
	void libvlc_video_set_marquee_int(Pointer p_mi, int option, int i_val);
	void libvlc_video_set_marquee_int(PointerByReference p_mi, int option, int i_val);
	@Deprecated 
	void libvlc_video_set_marquee_string(Pointer p_mi, int option, Pointer psz_text);
	void libvlc_video_set_marquee_string(PointerByReference p_mi, int option, String psz_text);
	void libvlc_video_set_marquee_string(PointerByReference p_mi, int option, Pointer psz_text);
	@Deprecated 
	int libvlc_video_get_logo_int(Pointer p_mi, int option);
	int libvlc_video_get_logo_int(PointerByReference p_mi, int option);
	@Deprecated 
	void libvlc_video_set_logo_int(Pointer p_mi, int option, int value);
	void libvlc_video_set_logo_int(PointerByReference p_mi, int option, int value);
	@Deprecated 
	void libvlc_video_set_logo_string(Pointer p_mi, int option, Pointer psz_value);
	void libvlc_video_set_logo_string(PointerByReference p_mi, int option, String psz_value);
	void libvlc_video_set_logo_string(PointerByReference p_mi, int option, Pointer psz_value);
	@Deprecated 
	int libvlc_video_get_adjust_int(Pointer p_mi, int option);
	int libvlc_video_get_adjust_int(PointerByReference p_mi, int option);
	@Deprecated 
	void libvlc_video_set_adjust_int(Pointer p_mi, int option, int value);
	void libvlc_video_set_adjust_int(PointerByReference p_mi, int option, int value);
	@Deprecated 
	float libvlc_video_get_adjust_float(Pointer p_mi, int option);
	float libvlc_video_get_adjust_float(PointerByReference p_mi, int option);
	@Deprecated 
	void libvlc_video_set_adjust_float(Pointer p_mi, int option, float value);
	void libvlc_video_set_adjust_float(PointerByReference p_mi, int option, float value);
	@Deprecated 
	libvlc_audio_output_t libvlc_audio_output_list_get(Pointer p_instance);
	libvlc_audio_output_t libvlc_audio_output_list_get(PointerByReference p_instance);
	void libvlc_audio_output_list_release(libvlc_audio_output_t p_list);
	@Deprecated 
	int libvlc_audio_output_set(Pointer p_mi, Pointer psz_name);
	int libvlc_audio_output_set(PointerByReference p_mi, String psz_name);
	int libvlc_audio_output_set(PointerByReference p_mi, Pointer psz_name);
	@Deprecated 
	libvlc_audio_output_device_t libvlc_audio_output_device_enum(Pointer mp);
	libvlc_audio_output_device_t libvlc_audio_output_device_enum(PointerByReference mp);
	@Deprecated 
	libvlc_audio_output_device_t libvlc_audio_output_device_list_get(Pointer p_instance, Pointer aout);
	libvlc_audio_output_device_t libvlc_audio_output_device_list_get(PointerByReference p_instance, String aout);
	libvlc_audio_output_device_t libvlc_audio_output_device_list_get(PointerByReference p_instance, Pointer aout);
	void libvlc_audio_output_device_list_release(libvlc_audio_output_device_t p_list);
	@Deprecated 
	void libvlc_audio_output_device_set(Pointer mp, Pointer module, Pointer device_id);
	void libvlc_audio_output_device_set(PointerByReference mp, String module, String device_id);
	void libvlc_audio_output_device_set(PointerByReference mp, Pointer module, Pointer device_id);
	@Deprecated 
	Pointer libvlc_audio_output_device_get(Pointer mp);
	Pointer libvlc_audio_output_device_get(PointerByReference mp);
	@Deprecated 
	void libvlc_audio_toggle_mute(Pointer p_mi);
	void libvlc_audio_toggle_mute(PointerByReference p_mi);
	@Deprecated 
	int libvlc_audio_get_mute(Pointer p_mi);
	int libvlc_audio_get_mute(PointerByReference p_mi);
	@Deprecated 
	void libvlc_audio_set_mute(Pointer p_mi, int status);
	void libvlc_audio_set_mute(PointerByReference p_mi, int status);
	@Deprecated 
	int libvlc_audio_get_volume(Pointer p_mi);
	int libvlc_audio_get_volume(PointerByReference p_mi);
	@Deprecated 
	int libvlc_audio_set_volume(Pointer p_mi, int i_volume);
	int libvlc_audio_set_volume(PointerByReference p_mi, int i_volume);
	@Deprecated 
	int libvlc_audio_get_track_count(Pointer p_mi);
	int libvlc_audio_get_track_count(PointerByReference p_mi);
	@Deprecated 
	libvlc_track_description_t libvlc_audio_get_track_description(Pointer p_mi);
	libvlc_track_description_t libvlc_audio_get_track_description(PointerByReference p_mi);
	@Deprecated 
	int libvlc_audio_get_track(Pointer p_mi);
	int libvlc_audio_get_track(PointerByReference p_mi);
	@Deprecated 
	int libvlc_audio_set_track(Pointer p_mi, int i_track);
	int libvlc_audio_set_track(PointerByReference p_mi, int i_track);
	@Deprecated 
	int libvlc_audio_get_channel(Pointer p_mi);
	int libvlc_audio_get_channel(PointerByReference p_mi);
	@Deprecated 
	int libvlc_audio_set_channel(Pointer p_mi, int channel);
	int libvlc_audio_set_channel(PointerByReference p_mi, int channel);
	@Deprecated 
	long libvlc_audio_get_delay(Pointer p_mi);
	long libvlc_audio_get_delay(PointerByReference p_mi);
	@Deprecated 
	int libvlc_audio_set_delay(Pointer p_mi, long i_delay);
	int libvlc_audio_set_delay(PointerByReference p_mi, long i_delay);
	int libvlc_audio_equalizer_get_preset_count();
	String libvlc_audio_equalizer_get_preset_name(int u_index);
	int libvlc_audio_equalizer_get_band_count();
	float libvlc_audio_equalizer_get_band_frequency(int u_index);
	PointerByReference libvlc_audio_equalizer_new();
	PointerByReference libvlc_audio_equalizer_new_from_preset(int u_index);
	@Deprecated 
	void libvlc_audio_equalizer_release(Pointer p_equalizer);
	void libvlc_audio_equalizer_release(PointerByReference p_equalizer);
	@Deprecated 
	int libvlc_audio_equalizer_set_preamp(Pointer p_equalizer, float f_preamp);
	int libvlc_audio_equalizer_set_preamp(PointerByReference p_equalizer, float f_preamp);
	@Deprecated 
	float libvlc_audio_equalizer_get_preamp(Pointer p_equalizer);
	float libvlc_audio_equalizer_get_preamp(PointerByReference p_equalizer);
	@Deprecated 
	int libvlc_audio_equalizer_set_amp_at_index(Pointer p_equalizer, float f_amp, int u_band);
	int libvlc_audio_equalizer_set_amp_at_index(PointerByReference p_equalizer, float f_amp, int u_band);
	@Deprecated 
	float libvlc_audio_equalizer_get_amp_at_index(Pointer p_equalizer, int u_band);
	float libvlc_audio_equalizer_get_amp_at_index(PointerByReference p_equalizer, int u_band);
	@Deprecated 
	int libvlc_media_player_set_equalizer(Pointer p_mi, Pointer p_equalizer);
	int libvlc_media_player_set_equalizer(PointerByReference p_mi, PointerByReference p_equalizer);
	@Deprecated 
	int libvlc_media_player_get_role(Pointer p_mi);
	int libvlc_media_player_get_role(PointerByReference p_mi);
	@Deprecated 
	int libvlc_media_player_set_role(Pointer p_mi, int role);
	int libvlc_media_player_set_role(PointerByReference p_mi, int role);
	@Deprecated 
	void libvlc_vlm_release(Pointer p_instance);
	void libvlc_vlm_release(PointerByReference p_instance);
	@Deprecated 
	int libvlc_vlm_add_broadcast(Pointer p_instance, Pointer psz_name, Pointer psz_input, Pointer psz_output, int i_options, PointerByReference ppsz_options, int b_enabled, int b_loop);
	int libvlc_vlm_add_broadcast(PointerByReference p_instance, String psz_name, String psz_input, String psz_output, int i_options, String ppsz_options[], int b_enabled, int b_loop);
	int libvlc_vlm_add_broadcast(PointerByReference p_instance, Pointer psz_name, Pointer psz_input, Pointer psz_output, int i_options, PointerByReference ppsz_options, int b_enabled, int b_loop);
	@Deprecated 
	int libvlc_vlm_add_vod(Pointer p_instance, Pointer psz_name, Pointer psz_input, int i_options, PointerByReference ppsz_options, int b_enabled, Pointer psz_mux);
	int libvlc_vlm_add_vod(PointerByReference p_instance, String psz_name, String psz_input, int i_options, String ppsz_options[], int b_enabled, String psz_mux);
	int libvlc_vlm_add_vod(PointerByReference p_instance, Pointer psz_name, Pointer psz_input, int i_options, PointerByReference ppsz_options, int b_enabled, Pointer psz_mux);
	@Deprecated 
	int libvlc_vlm_del_media(Pointer p_instance, Pointer psz_name);
	int libvlc_vlm_del_media(PointerByReference p_instance, String psz_name);
	int libvlc_vlm_del_media(PointerByReference p_instance, Pointer psz_name);
	@Deprecated 
	int libvlc_vlm_set_enabled(Pointer p_instance, Pointer psz_name, int b_enabled);
	int libvlc_vlm_set_enabled(PointerByReference p_instance, String psz_name, int b_enabled);
	int libvlc_vlm_set_enabled(PointerByReference p_instance, Pointer psz_name, int b_enabled);
	@Deprecated 
	int libvlc_vlm_set_output(Pointer p_instance, Pointer psz_name, Pointer psz_output);
	int libvlc_vlm_set_output(PointerByReference p_instance, String psz_name, String psz_output);
	int libvlc_vlm_set_output(PointerByReference p_instance, Pointer psz_name, Pointer psz_output);
	@Deprecated 
	int libvlc_vlm_set_input(Pointer p_instance, Pointer psz_name, Pointer psz_input);
	int libvlc_vlm_set_input(PointerByReference p_instance, String psz_name, String psz_input);
	int libvlc_vlm_set_input(PointerByReference p_instance, Pointer psz_name, Pointer psz_input);
	@Deprecated 
	int libvlc_vlm_add_input(Pointer p_instance, Pointer psz_name, Pointer psz_input);
	int libvlc_vlm_add_input(PointerByReference p_instance, String psz_name, String psz_input);
	int libvlc_vlm_add_input(PointerByReference p_instance, Pointer psz_name, Pointer psz_input);
	@Deprecated 
	int libvlc_vlm_set_loop(Pointer p_instance, Pointer psz_name, int b_loop);
	int libvlc_vlm_set_loop(PointerByReference p_instance, String psz_name, int b_loop);
	int libvlc_vlm_set_loop(PointerByReference p_instance, Pointer psz_name, int b_loop);
	@Deprecated 
	int libvlc_vlm_set_mux(Pointer p_instance, Pointer psz_name, Pointer psz_mux);
	int libvlc_vlm_set_mux(PointerByReference p_instance, String psz_name, String psz_mux);
	int libvlc_vlm_set_mux(PointerByReference p_instance, Pointer psz_name, Pointer psz_mux);
	@Deprecated 
	int libvlc_vlm_change_media(Pointer p_instance, Pointer psz_name, Pointer psz_input, Pointer psz_output, int i_options, PointerByReference ppsz_options, int b_enabled, int b_loop);
	int libvlc_vlm_change_media(PointerByReference p_instance, String psz_name, String psz_input, String psz_output, int i_options, String ppsz_options[], int b_enabled, int b_loop);
	int libvlc_vlm_change_media(PointerByReference p_instance, Pointer psz_name, Pointer psz_input, Pointer psz_output, int i_options, PointerByReference ppsz_options, int b_enabled, int b_loop);
	@Deprecated 
	int libvlc_vlm_play_media(Pointer p_instance, Pointer psz_name);
	int libvlc_vlm_play_media(PointerByReference p_instance, String psz_name);
	int libvlc_vlm_play_media(PointerByReference p_instance, Pointer psz_name);
	@Deprecated 
	int libvlc_vlm_stop_media(Pointer p_instance, Pointer psz_name);
	int libvlc_vlm_stop_media(PointerByReference p_instance, String psz_name);
	int libvlc_vlm_stop_media(PointerByReference p_instance, Pointer psz_name);
	@Deprecated 
	int libvlc_vlm_pause_media(Pointer p_instance, Pointer psz_name);
	int libvlc_vlm_pause_media(PointerByReference p_instance, String psz_name);
	int libvlc_vlm_pause_media(PointerByReference p_instance, Pointer psz_name);
	@Deprecated 
	int libvlc_vlm_seek_media(Pointer p_instance, Pointer psz_name, float f_percentage);
	int libvlc_vlm_seek_media(PointerByReference p_instance, String psz_name, float f_percentage);
	int libvlc_vlm_seek_media(PointerByReference p_instance, Pointer psz_name, float f_percentage);
	@Deprecated 
	String libvlc_vlm_show_media(Pointer p_instance, Pointer psz_name);
	String libvlc_vlm_show_media(PointerByReference p_instance, String psz_name);
	String libvlc_vlm_show_media(PointerByReference p_instance, Pointer psz_name);
	@Deprecated 
	float libvlc_vlm_get_media_instance_position(Pointer p_instance, Pointer psz_name, int i_instance);
	float libvlc_vlm_get_media_instance_position(PointerByReference p_instance, String psz_name, int i_instance);
	float libvlc_vlm_get_media_instance_position(PointerByReference p_instance, Pointer psz_name, int i_instance);
	@Deprecated 
	int libvlc_vlm_get_media_instance_time(Pointer p_instance, Pointer psz_name, int i_instance);
	int libvlc_vlm_get_media_instance_time(PointerByReference p_instance, String psz_name, int i_instance);
	int libvlc_vlm_get_media_instance_time(PointerByReference p_instance, Pointer psz_name, int i_instance);
	@Deprecated 
	int libvlc_vlm_get_media_instance_length(Pointer p_instance, Pointer psz_name, int i_instance);
	int libvlc_vlm_get_media_instance_length(PointerByReference p_instance, String psz_name, int i_instance);
	int libvlc_vlm_get_media_instance_length(PointerByReference p_instance, Pointer psz_name, int i_instance);
	@Deprecated 
	int libvlc_vlm_get_media_instance_rate(Pointer p_instance, Pointer psz_name, int i_instance);
	int libvlc_vlm_get_media_instance_rate(PointerByReference p_instance, String psz_name, int i_instance);
	int libvlc_vlm_get_media_instance_rate(PointerByReference p_instance, Pointer psz_name, int i_instance);
	@Deprecated 
	PointerByReference libvlc_vlm_get_event_manager(Pointer p_instance);
	PointerByReference libvlc_vlm_get_event_manager(PointerByReference p_instance);
	/** Pointer to unknown (opaque) type */
	public static class libvlc_renderer_item_t extends PointerType {
		public libvlc_renderer_item_t(Pointer address) {
			super(address);
		}
		public libvlc_renderer_item_t() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class libvlc_media_read_cb extends PointerType {
		public libvlc_media_read_cb(Pointer address) {
			super(address);
		}
		public libvlc_media_read_cb() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class libvlc_instance_t extends PointerType {
		public libvlc_instance_t(Pointer address) {
			super(address);
		}
		public libvlc_instance_t() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class libvlc_log_t extends PointerType {
		public libvlc_log_t(Pointer address) {
			super(address);
		}
		public libvlc_log_t() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class libvlc_media_player_t extends PointerType {
		public libvlc_media_player_t(Pointer address) {
			super(address);
		}
		public libvlc_media_player_t() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class libvlc_event_t extends PointerType {
		public libvlc_event_t(Pointer address) {
			super(address);
		}
		public libvlc_event_t() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class libvlc_event_manager_t extends PointerType {
		public libvlc_event_manager_t(Pointer address) {
			super(address);
		}
		public libvlc_event_manager_t() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class FILE extends PointerType {
		public FILE(Pointer address) {
			super(address);
		}
		public FILE() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class libvlc_media_t extends PointerType {
		public libvlc_media_t(Pointer address) {
			super(address);
		}
		public libvlc_media_t() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class libvlc_equalizer_t extends PointerType {
		public libvlc_equalizer_t(Pointer address) {
			super(address);
		}
		public libvlc_equalizer_t() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class libvlc_media_list_t extends PointerType {
		public libvlc_media_list_t(Pointer address) {
			super(address);
		}
		public libvlc_media_list_t() {
			super();
		}
	};
}
